stages:
  - build
  - documentation

openSUSE:
  stage: build
  image: opensuse/tumbleweed

  before_script:
    - zypper in -y cmake gcc-c++ gcc git libaec-devel libtar-devel
    - git clone --recurse-submodules https://github.com/deepsig/libsigmf.git
    - cd libsigmf
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make -j $(nproc --all)
    - make install
    - cd ../..

  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    - make
    - make install

debian:
  stage: build
  image: debian:buster
  variables:
        DEBIAN_FRONTEND: "noninteractive"

  before_script: 
    - apt-get update -qq -y
    - apt-get install -q -y cmake g++ gcc git libaec-dev libtar-dev
    - git clone --recurse-submodules https://github.com/deepsig/libsigmf.git
    - cd libsigmf
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make -j $(nproc --all)
    - make install
    - cd ../..

  script:
    - mkdir -p build
    - cd build
    - cmake  ..
    - make
    - make install
    - ldconfig

pages:
  stage: documentation
  image: debian:buster

  before_script:
    - apt-get update -qq -y
    - apt-get install -q -y cmake g++ gcc git libaec-dev libtar-dev
    - git clone --recurse-submodules https://github.com/deepsig/libsigmf.git
    - cd libsigmf
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make -j $(nproc --all)
    - make install
    - cd ../..

  script:
    - mkdir -p build
    - cd build
    - rm -rf *
    - cmake  .. 
    - make doxygen_target
    - cd ..
    - rm -rf public/*
    - mv build/docs/doxygen/html public/

  artifacts:
    paths:
      - public
  only:
    - master

