stages:
  - building
  - documentation

opensuse_build:
  image: opensuse/tumbleweed

  before_script:
      - zypper in -y cmake gcc-c++ gcc git flatbuffers-devel nlohmann_json-devel libtar-devel

  stage: building
  script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        - make
        - make install

ubuntu_1810_build:
  image: ubuntu:18.10
  
  variables:
        DEBIAN_FRONTEND: "noninteractive"

  before_script: 
        - apt-get update -qq -y
        - apt-get install -qq -y software-properties-common
        - add-apt-repository ppa:team-xbmc/ppa 
        - apt-get update -qq -y && apt-get install -q -y cmake g++ gcc git libtar-dev
  stage: building
  allow_failure: true
  script:
        - mkdir -p build
        - cd build
        - cmake  ..
        - make
        - make install
        - ldconfig

pages:
  image: opensuse/tumbleweed

  before_script:
      - zypper in -y cmake gcc-c++ gcc git flatbuffers-devel nlohmann_json-devel doxygen libtar-dev

  stage: documentation
  script:
      - mkdir -p build
      - cd build
      - rm -rf *
      - cmake  .. 
      - make doxygen_target
      - cd ..
      - rm -rf public/*
      - mv build/docs/doxygen/html public/  
  artifacts:
      paths:
      - public
  only:
  - master

